version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=user1
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=shy_database

volumes:
  postgresql_data:
    driver: local
